name: Build APK 215-FINAL-SHIELD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Setup
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev \
            build-essential python3-dev ant lld libsqlite3-dev
          
          pip install --upgrade pip
          pip install "Cython<3.0" buildozer kivy pillow pyjnius

          # [핵심 방어] 라이선스 무조건 승인 파일 생성
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo -e "8933bad161af9178b11909454ede1222ad145220\nd56f5187479451eabf01fb74301353a168261936" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          
          export BUILDOZER_ALLOW_KIVY_MASTER=1
          buildozer -v android debug
        shell: bash

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PristonTale-Final-APK
          path: bin/*.apk
